package br.gov.pi.tce.whitedragon.util;

import java.io.IOException;
import java.io.InputStream;
import java.util.Properties;

import br.gov.pi.tce.TceJsfUtil.TceNegocioException;

public enum Bundle {

	NOME_APLICACAO,	
	ID_APLICACAO,
	VERSION,
	ANO_INICIAL_CADASTRO, 
	MSG_VALIDADE_USUARIO_EXPIRADA,

	TAM_MAX_UPLOAD,

	STATUS_CONTRATO_EM_CADASTRO,
	STATUS_CONTRATO_AGUARDA_EXECUCAO,
	STATUS_CONTRATO_EM_EXECUCAO,
	STATUS_CONTRATO_ENCERRADO,
	STATUS_CONTRATO_SUSPENSO,
	STATUS_CONTRATO_RESCINDIDO,

	PROCEDIMENTO_LICITACAO,
	PROCEDIMENTO_ADESAO,
	PROCEDIMENTO_DISPENSA,
	PROCEDIMENTO_INEXIGIBILIDADE, 

	MODALIDADE_CONCORRENCIA,
	MODALIDADE_TOMADA_DE_PRECO,
	MODALIDADE_CONVITE,
	MODALIDADE_LEILAO,
	MODALIDADE_PREGAO,
	MODALIDADE_PREGAO_ELETRONICO,
	MODALIDADE_RDC,

	TIPO_PUBLICACAO_DIARIO_OFICIAL_UNIAO,
	TIPO_PUBLICACAO_DIARIO_OFICIAL_ESTADO,
	TIPO_PUBLICACAO_DIARIO_OFICIAL_MUNICIPIOS,
	TIPO_PUBLICACAO_DIARIO_OFICIAL_PROPRIO,
	TIPO_PUBLICACAO_JORNAL,
	TIPO_PUBLICACAO_INTERNET,
	TIPO_PUBLICACAO_QUADRO_AVISOS,
	TIPO_PUBLICACAO_OUTROS,

	TIPO_ANEXO_INSTRUMENTO_CONTRATUAL,
	TIPO_ANEXO_ADITIVO,
	TIPO_ANEXO_ATA_ADERIDA,
	TIPO_ANEXO_OUTRO,

	TIPO_CATEGORIA_INCIDENTE_TERMO_ADITIVO,
	TIPO_CATEGORIA_INCIDENTE_APOSTILAMENTO,
	TIPO_CATEGORIA_INCIDENTE_SANCAO,
	TIPO_CATEGORIA_INCIDENTE_SUSPENSAO,
	TIPO_CATEGORIA_INCIDENTE_REVOGACAO_SUSPENSAO,
	TIPO_CATEGORIA_INCIDENTE_RESCISAO,
	TIPO_CATEGORIA_INCIDENTE_OUTRO,

	TIPO_INCIDENTE_TERMO_ADITIVO_ALTERACAO_QUANTITATIVA,
	TIPO_INCIDENTE_TERMO_ADITIVO_ALTERACAO_QUALITATIVA,
	TIPO_INCIDENTE_TERMO_ADITIVO_REVISAO_ALINHAMENTO,
	TIPO_INCIDENTE_TERMO_ADITIVO_REPACTUACAO,
	TIPO_INCIDENTE_TERMO_ADITIVO_REAJUSTE_PRECO_PREVISTO,
	TIPO_INCIDENTE_TERMO_ADITIVO_ATUALIZACAO_MONETARIA,
	TIPO_INCIDENTE_TERMO_ADITIVO_PRORROGACAO_VIGENCIA,
	TIPO_INCIDENTE_TERMO_ADITIVO_OUTRO,

	TIPO_INCIDENTE_APOSTILAMENTO_REAJUSTE_PRECO_PREVISTO,
	TIPO_INCIDENTE_APOSTILAMENTO_ATUALIZACAO_MONETARIA,
	TIPO_INCIDENTE_APOSTILAMENTO_COMPENSACOES,
	TIPO_INCIDENTE_APOSTILAMENTO_PENALIZACOES_FINANCEIRAS,
	TIPO_INCIDENTE_APOSTILAMENTO_DOTACOES_ORCAMENTARIAS_SUPLEMENTARES,
	TIPO_INCIDENTE_APOSTILAMENTO_OUTRO,

	TIPO_INCIDENTE_SANCAO_ADVERTENCIA,
	TIPO_INCIDENTE_SANCAO_MULTA,
	TIPO_INCIDENTE_SANCAO_SUSPENSAO_TEMPORARIA,
	TIPO_INCIDENTE_SANCAO_IMPEDIMENTO_CONTRATAR,
	TIPO_INCIDENTE_SANCAO_DECLARACAO_INIDONEIDADE,

	TIPO_INCIDENTE_SUSPENSAO,
	TIPO_INCIDENTE_REVOGA_SUSPENSAO,

	TIPO_INCIDENTE_RESCISAO,
	TIPO_INCIDENTE_OUTRO,

	STATUS_LICITACAO_FINALIZADA,

	MSG_ERRO_AUSENCIA_REPRESENTANTE_CONTRATANTE,
	MSG_ERRO_AUSENCIA_GESTOR_CONTRATO,
	MSG_ERRO_AUSENCIA_FISCAL_CONTRATO,
	MSG_ERRO_AUSENCIA_PUBLICACAO,
	MSG_ERRO_AUSENCIA_INSTRUMENTO_CONTRATUAL,
	MSG_ERRO_AUSENCIA_ITEM,

	MSG_ERRO_BAIXAR_ARQUIVO,

	FIM

;

	public String mensagem() {
        Properties properties = new Properties();
        InputStream inputStream = null;
        try {
            String fileName = "/messages.properties";
            inputStream = getClass().getResourceAsStream(fileName);

            if (inputStream == null) {
            	throw new TceNegocioException("Erro de sistema: arquivo de mensagens não foi encontrado.");
            }
            properties.load(inputStream);

            String msg = properties.getProperty(name());
			if (msg == null) {
				throw new TceNegocioException(name() + ": Código Mensagem não encontrado.");
			}
			return msg;

        } catch (IOException e) {
        	System.out.println("ContratosWEB: "+e.getMessage());
        	throw new TceNegocioException("Erro de sistema: arquivo de mensagens não foi encontrado.");
        }

	}

	public Long longValue() {
		return Long.parseLong(mensagem());
	}
	
	public Integer intValue() {
		return Integer.parseInt(mensagem());
	}

}
